# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('bitrate', models.CharField(blank=True, max_length=255, null=True)),
                ('disco_num', models.IntegerField(blank=True, null=True)),
                ('disco_total', models.IntegerField(blank=True, null=True)),
                ('duracao', models.FloatField(blank=True, null=True)),
                ('tamanho', models.FloatField(blank=True, null=True)),
                ('genero', models.CharField(default='Outro', max_length=255, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('convidado', models.CharField(blank=True, max_length=255, null=True)),
                ('produtor', models.CharField(blank=True, max_length=255, null=True)),
                ('instrumental', models.CharField(blank=True, max_length=255, null=True)),
                ('outros', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=255)),
                ('ficheiro', models.FileField(upload_to='uploads/')),
                ('data_entrada', models.DateField(default=datetime.datetime(2017, 11, 19, 17, 58, 55, 120500, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=32)),
                ('is_file', models.BooleanField(default=False)),
                ('data_entrada', models.DateField(default=datetime.datetime(2017, 11, 19, 17, 58, 55, 120500, tzinfo=utc))),
                ('ficheiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yotlanga.Ficheiro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('senha', models.CharField(max_length=1024)),
                ('sexo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True, unique=True)),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField(default=datetime.datetime(2017, 11, 19, 17, 58, 55, 120500, tzinfo=utc))),
                ('is_online', models.BooleanField(default=False)),
                ('status', models.CharField(default='activo', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='publicacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yotlanga.Usuario'),
        ),
        migrations.AddField(
            model_name='ficheiro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yotlanga.Usuario'),
        ),
        migrations.AddField(
            model_name='audiotag',
            name='ficheiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yotlanga.Ficheiro'),
        ),
    ]
